### ISSUE TITLE
Test against Django 2.0

### ISSUE THREAD

**Issue by sloria** [chrisseto/django-include#21]

**Comment by Johnetordoff** [comment]
@sloria We are soon upgrading the OSF to Django 2.0.13 and this is incompatible, would it be easy to upgrade this?

**Comment by sloria** [comment]
I'm not sure..haven't looked into it. I think @chrisseto is planning on fixing Django 2 compat?

**Comment by chrisseto** [comment]
It is on my todo list!
(Also considering changing the name as `django-include` only brings up information about django's include function...)

@Johnetordoff is there a timeline for the upgrade?

**Comment by Johnetordoff** [comment]
@chrisseto well it's not in the current sprint, but we would need it by the start working on this ticket by the beginning if the next one. 

So March 10th, if you can't get it done by then, no problem we can just fork it. Thanks!
